import type { FormField } from "@/types"

// src/pages/biodata/biodataFields.tsx
export const bioDataFields: FormField[] = [
  {
    id: "fullName",
    name: "fullName",
    readOnly: false,
    labelText: "Full Name",
    type: "text",
    placeholder: "Your full name",
    required: true,
  },
  {
    id: "dateOfBirth",
    name: "dateOfBirth",
    readOnly: false,
    labelText: "Date of Birth",
    type: "date",
    required: true,
  },
  {
    id: "gender",
    name: "gender",
    readOnly: false,
    labelText: "Gender",
    type: "select",
    options: [
      { labelText: "Male", value: "male" },
      { labelText: "Female", value: "female" },
      { labelText: "Non-binary", value: "non-binary" },
      { labelText: "Prefer not to say", value: "not-specified" },
    ],
    required: true,
  },
  {
    id: "phone",
    name: "phone",
    readOnly: false,
    labelText: "Phone Number",
    type: "tel",
    placeholder: "+1 (123) 456-7890",
    required: true,
  },
  {
    id: "email",
    name: "email",
    readOnly: false,
    labelText: "Email Address",
    type: "email",
    placeholder: "your@email.com",
    required: true,
  },
  {
    id: "address",
    name: "address",
    readOnly: false,
    labelText: "Address",
    type: "textarea",
    placeholder: "Your full address",
    required: true,
  },
  {
    id: "education",
    name: "education",
    readOnly: false,
    labelText: "Highest Education",
    type: "select",
    options: [
      { labelText: "High School", value: "high-school" },
      { labelText: "Associate's Degree", value: "associates" },
      { labelText: "Bachelor's Degree", value: "bachelors" },
      { labelText: "Master's Degree", value: "masters" },
      { labelText: "PhD/Doctorate", value: "doctorate" },
      { labelText: "Other", value: "other" },
    ],
    required: true,
  },
  {
    id: "fieldOfStudy",
    name: "fieldOfStudy",
    readOnly: false,
    labelText: "Field of Study",
    type: "text",
    placeholder: "e.g. Computer Science",
  },
  {
    id: "yearsOfExperience",
    name: "yearsOfExperience",
    readOnly: false,
    labelText: "Years of Experience",
    type: "number",
    min: 0,
    max: 50,
  },
  {
    id: "skillsInterests",
    name: "skillsInterests",
    readOnly: false,
    labelText: "Technical Skills & Interests",
    type: "textarea",
    placeholder: "List your technical skills and areas of interest",
    helperText: "Separate skills with commas (e.g. React, Node.js, Python)",
  },
  {
    id: "portfolioUrl",
    name: "portfolioUrl",
    readOnly: false,
    labelText: "Portfolio URL",
    type: "url",
    placeholder: "https://yourportfolio.com",
  },
  {
    id: "githubUrl",
    name: "githubUrl",
    readOnly: false,
    labelText: "GitHub URL",
    type: "url",
    placeholder: "https://github.com/yourusername",
  },
  {
    id: "linkedinUrl",
    name: "linkedinUrl",
    readOnly: false,
    labelText: "LinkedIn URL",
    type: "url",
    placeholder: "https://linkedin.com/in/yourusername",
  },
  {
    id: "additionalInfo",
    name: "additionalInfo",
    readOnly: false,
    labelText: "Additional Information",
    type: "textarea",
    placeholder: "Any additional information you'd like to share",
  },
]
